#ifndef SHRIMP_IOT_ARDUINO_SECRETS_H
#define SHRIMP_IOT_ARDUINO_SECRETS_H

// Copy this file to arduino_secrets.h and replace every placeholder.
// Never commit arduino_secrets.h.
#define SECRET_WIFI_SSID "YOUR_WIFI_SSID"
#define SECRET_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define SECRET_IOT_API_KEY "YOUR_LONG_RANDOM_IOT_API_KEY"
#define SECRET_SETUP_AP_PASSWORD "YOUR_UNIQUE_12_TO_63_CHAR_SETUP_PASSWORD"
#define SECRET_MQTT_HOST "YOUR_HIVEMQ_CLUSTER_HOST"
#define SECRET_MQTT_USERNAME "YOUR_DEVICE_MQTT_USERNAME"
#define SECRET_MQTT_PASSWORD "YOUR_DEVICE_MQTT_PASSWORD"

#endif
