-- Baseline generated from the verified local PostgreSQL schema.
-- Existing databases are baselined at V1; empty databases execute this file.

CREATE TABLE public."alerts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "alert_type" character varying(50) NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "device_id" character varying(100) NOT NULL,
    "message" character varying(500) NOT NULL,
    "resolved_at" timestamp(6) without time zone,
    "resolved_by" character varying(100),
    "severity" character varying(20) NOT NULL,
    "status" character varying(20) NOT NULL
);

CREATE TABLE public."audit_logs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "action" character varying(100) NOT NULL,
    "actor_role" character varying(30),
    "actor_username" character varying(100),
    "created_at" timestamp(6) without time zone NOT NULL,
    "device_id" character varying(100),
    "ip_address" character varying(80),
    "message" character varying(1000),
    "pond_id" bigint,
    "target_id" character varying(150),
    "target_type" character varying(100)
);

CREATE TABLE public."auth_tokens" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "expires_at" timestamp(6) without time zone NOT NULL,
    "revoked" boolean NOT NULL,
    "token" character varying(255) NOT NULL,
    "user_id" bigint NOT NULL
);

CREATE TABLE public."chat_messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "content" text NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "device_id" character varying(100),
    "role" character varying(20) NOT NULL,
    "session_id" bigint NOT NULL
);

CREATE TABLE public."chat_sessions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "device_id" character varying(100),
    "title" character varying(200) NOT NULL,
    "updated_at" timestamp(6) without time zone NOT NULL,
    "user_id" bigint NOT NULL
);

CREATE TABLE public."control_scenarios" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "action" character varying(255) NOT NULL,
    "auto_off_enabled" boolean NOT NULL,
    "condition_parameter" character varying(255) NOT NULL,
    "cooldown_seconds" bigint,
    "created_at" timestamp(6) without time zone NOT NULL,
    "enabled" boolean NOT NULL,
    "max_runtime_seconds" bigint,
    "operator" character varying(255) NOT NULL,
    "relay_no" integer NOT NULL,
    "threshold_value" double precision NOT NULL,
    "updated_at" timestamp(6) without time zone,
    "pond_id" bigint NOT NULL
);

CREATE TABLE public."device_commands" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ack_at" timestamp(6) without time zone,
    "action" character varying(10) NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "device_id" character varying(100) NOT NULL,
    "expires_at" timestamp(6) without time zone,
    "message" character varying(500),
    "relay_no" integer NOT NULL,
    "requested_by" character varying(100),
    "sent_at" timestamp(6) without time zone,
    "source" character varying(30),
    "status" character varying(20) NOT NULL
);

CREATE TABLE public."device_latest_states" (
    "device_id" character varying(100) NOT NULL,
    "ai_message" character varying(500),
    "anomaly_status" character varying(20),
    "do_value" double precision,
    "ec_value" double precision,
    "final_status" character varying(20),
    "latest_reading_id" bigint,
    "message" character varying(500),
    "ml_status" character varying(20),
    "ph" double precision,
    "recommended_action" character varying(500),
    "rule_status" character varying(20),
    "salinity" double precision,
    "status" character varying(20) NOT NULL,
    "temperature" double precision,
    "updated_at" timestamp(6) without time zone NOT NULL
);

CREATE TABLE public."device_operation_configs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "auto_remeasure_enabled" boolean,
    "cooldown_minutes" integer NOT NULL,
    "device_id" character varying(100) NOT NULL,
    "fill_duration_seconds" integer NOT NULL,
    "freshwater_duration_seconds" integer NOT NULL,
    "max_retry_count" integer NOT NULL,
    "measurement_drain_duration_seconds" integer NOT NULL,
    "measurement_duration_seconds" integer NOT NULL,
    "mixing_wait_seconds" integer NOT NULL,
    "operation_mode" character varying(20) NOT NULL,
    "reading_max_age_seconds" integer,
    "safety_lock_enabled" boolean,
    "salinity_auto_enabled" boolean NOT NULL,
    "salinity_drain_duration_seconds" integer NOT NULL,
    "salinity_high_threshold" double precision NOT NULL,
    "salinity_stop_threshold" double precision NOT NULL,
    "stabilizing_seconds" integer NOT NULL,
    "updated_at" timestamp(6) without time zone NOT NULL,
    "updated_by" character varying(100)
);

CREATE TABLE public."device_provisioning" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "claim_code_expires_at" timestamp(6) without time zone,
    "claim_code_hash" character varying(64),
    "claim_status" character varying(20) NOT NULL,
    "claimed_at" timestamp(6) without time zone,
    "created_at" timestamp(6) without time zone NOT NULL,
    "issued_at" timestamp(6) without time zone,
    "revoked_at" timestamp(6) without time zone,
    "updated_at" timestamp(6) without time zone NOT NULL,
    "claimed_by_user_id" bigint,
    "claimed_pond_id" bigint,
    "device_id" bigint NOT NULL
);

CREATE TABLE public."device_relays" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "locked" boolean,
    "locked_at" timestamp(6) without time zone,
    "locked_by" character varying(100),
    "name" character varying(150) NOT NULL,
    "pin" integer,
    "relay_no" integer NOT NULL,
    "relay_type" character varying(50),
    "status" character varying(30) NOT NULL,
    "device_id" bigint NOT NULL
);

CREATE TABLE public."device_sensors" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "max_threshold" double precision,
    "min_threshold" double precision,
    "name" character varying(150) NOT NULL,
    "pin" character varying(30),
    "sensor_type" character varying(50) NOT NULL,
    "status" character varying(30) NOT NULL,
    "device_id" bigint NOT NULL
);

CREATE TABLE public."devices" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "connection_status" character varying(30),
    "created_at" timestamp(6) without time zone NOT NULL,
    "device_id" character varying(100) NOT NULL,
    "installation_position" character varying(255),
    "last_seen_at" timestamp(6) without time zone,
    "latitude" double precision,
    "longitude" double precision,
    "name" character varying(150) NOT NULL,
    "status" character varying(30) NOT NULL,
    "pond_id" bigint
);

CREATE TABLE public."measurement_cycles" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "completed_at" timestamp(6) without time zone,
    "device_id" character varying(100) NOT NULL,
    "message" character varying(500),
    "sample_source" character varying(255),
    "started_at" timestamp(6) without time zone NOT NULL,
    "started_by" character varying(100),
    "status" character varying(30) NOT NULL
);

CREATE TABLE public."notification_logs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "alert_type" character varying(50),
    "channel" character varying(30),
    "cooldown_until" timestamp(6) without time zone,
    "created_at" timestamp(6) without time zone NOT NULL,
    "device_id" character varying(100),
    "event_key" character varying(160),
    "message" character varying(500),
    "provider_response" character varying(1000),
    "read_at" timestamp(6) without time zone,
    "read_by" character varying(100),
    "read_flag" boolean NOT NULL,
    "recipient" character varying(150),
    "recipient_user_id" bigint,
    "recipient_username" character varying(100),
    "severity" character varying(30),
    "status" character varying(40),
    "suppressed" boolean NOT NULL,
    "suppression_reason" character varying(500)
);

CREATE TABLE public."ponds" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "area_square_meters" double precision,
    "created_at" timestamp(6) without time zone NOT NULL,
    "description" character varying(500),
    "latitude" double precision,
    "location" character varying(255),
    "longitude" double precision,
    "name" character varying(150) NOT NULL,
    "pond_type" character varying(100),
    "region" character varying(100),
    "species_type" character varying(100),
    "status" character varying(30),
    "water_volume_cubic_meters" double precision
);

CREATE TABLE public."relay_states" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "current_state" character varying(255) NOT NULL,
    "device_id" character varying(255) NOT NULL,
    "last_command_id" bigint,
    "last_updated_at" timestamp(6) without time zone NOT NULL,
    "relay_name" character varying(255),
    "relay_no" integer NOT NULL
);

CREATE TABLE public."salinity_correction_cycles" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "completed_at" timestamp(6) without time zone,
    "device_id" character varying(100) NOT NULL,
    "latest_salinity" double precision,
    "max_retry_count" integer NOT NULL,
    "message" character varying(500),
    "retry_count" integer NOT NULL,
    "start_salinity" double precision,
    "started_at" timestamp(6) without time zone NOT NULL,
    "status" character varying(40) NOT NULL,
    "target_salinity" double precision,
    "triggered_by" character varying(100)
);

CREATE TABLE public."sensor_calibrations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "active" boolean NOT NULL,
    "calibration_point_1" double precision,
    "calibration_point_2" double precision,
    "created_at" timestamp(6) without time zone NOT NULL,
    "device_id" character varying(100) NOT NULL,
    "note" character varying(1000),
    "offset_value" double precision NOT NULL,
    "sensor_type" character varying(50) NOT NULL,
    "slope_value" double precision NOT NULL,
    "updated_at" timestamp(6) without time zone NOT NULL
);

CREATE TABLE public."sensor_readings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ai_message" character varying(500),
    "anomaly_status" character varying(20),
    "created_at" timestamp(6) without time zone NOT NULL,
    "device_id" character varying(100) NOT NULL,
    "do_value" double precision,
    "ec_value" double precision,
    "final_status" character varying(20),
    "message" character varying(500),
    "ml_status" character varying(20),
    "ph" double precision,
    "recommended_action" character varying(500),
    "rule_status" character varying(20),
    "salinity" double precision,
    "status" character varying(20) NOT NULL,
    "temperature" double precision
);

CREATE TABLE public."threshold_configs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "enabled" boolean NOT NULL,
    "max_value" double precision NOT NULL,
    "min_value" double precision NOT NULL,
    "parameter_name" character varying(50) NOT NULL,
    "severity" character varying(30) NOT NULL,
    "updated_at" timestamp(6) without time zone,
    "updated_by" character varying(100),
    "pond_id" bigint NOT NULL
);

CREATE TABLE public."user_pond_access" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "access_type" character varying(30) NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "pond_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);

CREATE TABLE public."users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "active" boolean NOT NULL,
    "approval_status" character varying(30),
    "approved_at" timestamp(6) without time zone,
    "approved_by" character varying(100),
    "created_at" timestamp(6) without time zone NOT NULL,
    "email" character varying(150),
    "full_name" character varying(150) NOT NULL,
    "password_hash" character varying(255) NOT NULL,
    "phone" character varying(30),
    "role" character varying(30) NOT NULL,
    "username" character varying(100) NOT NULL
);

ALTER TABLE ONLY public."alerts" ADD CONSTRAINT "alerts_alert_type_check" CHECK (alert_type::text = ANY (ARRAY['TEMP_LOW'::character varying, 'TEMP_HIGH'::character varying, 'PH_LOW'::character varying, 'PH_HIGH'::character varying, 'SALINITY_LOW'::character varying, 'SALINITY_HIGH'::character varying, 'DO_LOW'::character varying, 'DEVICE_OVER_RUNTIME'::character varying, 'DEVICE_OFFLINE'::character varying]::text[]));
ALTER TABLE ONLY public."alerts" ADD CONSTRAINT "alerts_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."alerts" ADD CONSTRAINT "alerts_severity_check" CHECK (severity::text = ANY (ARRAY['INFO'::character varying, 'WARNING'::character varying, 'DANGER'::character varying]::text[]));
ALTER TABLE ONLY public."alerts" ADD CONSTRAINT "alerts_status_check" CHECK (status::text = ANY (ARRAY['OPEN'::character varying, 'RESOLVED'::character varying]::text[]));
ALTER TABLE ONLY public."audit_logs" ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."auth_tokens" ADD CONSTRAINT "auth_tokens_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."auth_tokens" ADD CONSTRAINT "uk8eqyhmaqeqakfjut8vpdfm6cr" UNIQUE (token);
ALTER TABLE ONLY public."chat_messages" ADD CONSTRAINT "chat_messages_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."chat_messages" ADD CONSTRAINT "chat_messages_role_check" CHECK (role::text = ANY (ARRAY['USER'::character varying, 'ASSISTANT'::character varying]::text[]));
ALTER TABLE ONLY public."chat_sessions" ADD CONSTRAINT "chat_sessions_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."control_scenarios" ADD CONSTRAINT "control_scenarios_action_check" CHECK (action::text = ANY (ARRAY['ON'::character varying, 'OFF'::character varying]::text[]));
ALTER TABLE ONLY public."control_scenarios" ADD CONSTRAINT "control_scenarios_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."device_commands" ADD CONSTRAINT "device_commands_action_check" CHECK (action::text = ANY (ARRAY['ON'::character varying, 'OFF'::character varying]::text[]));
ALTER TABLE ONLY public."device_commands" ADD CONSTRAINT "device_commands_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."device_commands" ADD CONSTRAINT "device_commands_status_check" CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'SENT'::character varying, 'ACK'::character varying, 'FAILED'::character varying, 'EXPIRED'::character varying]::text[]));
ALTER TABLE ONLY public."device_latest_states" ADD CONSTRAINT "device_latest_states_pkey" PRIMARY KEY (device_id);
ALTER TABLE ONLY public."device_latest_states" ADD CONSTRAINT "device_latest_states_status_check" CHECK (status::text = ANY (ARRAY['NORMAL'::character varying, 'WARNING'::character varying, 'DANGER'::character varying]::text[]));
ALTER TABLE ONLY public."device_operation_configs" ADD CONSTRAINT "device_operation_configs_operation_mode_check" CHECK (operation_mode::text = ANY (ARRAY['MANUAL'::character varying, 'AI_AUTO'::character varying]::text[]));
ALTER TABLE ONLY public."device_operation_configs" ADD CONSTRAINT "device_operation_configs_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."device_operation_configs" ADD CONSTRAINT "ukica60mi7warbqx7d3gckhrlb6" UNIQUE (device_id);
ALTER TABLE ONLY public."device_provisioning" ADD CONSTRAINT "device_provisioning_claim_status_check" CHECK (claim_status::text = ANY (ARRAY['UNCLAIMED'::character varying, 'CLAIMED'::character varying, 'REVOKED'::character varying]::text[]));
ALTER TABLE ONLY public."device_provisioning" ADD CONSTRAINT "device_provisioning_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."device_provisioning" ADD CONSTRAINT "ukidd8yngh2t7ubg8dh937epw8c" UNIQUE (device_id);
ALTER TABLE ONLY public."device_relays" ADD CONSTRAINT "device_relays_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."device_relays" ADD CONSTRAINT "ukr7f3bn4ds3dmc9219up1wga51" UNIQUE (device_id, relay_no);
ALTER TABLE ONLY public."device_sensors" ADD CONSTRAINT "device_sensors_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."device_sensors" ADD CONSTRAINT "uk15ydasy2gwmdguuh8sp706l57" UNIQUE (device_id, sensor_type);
ALTER TABLE ONLY public."devices" ADD CONSTRAINT "devices_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."devices" ADD CONSTRAINT "ukkl1viut5wsyxgnd1t3wqf9hbu" UNIQUE (device_id);
ALTER TABLE ONLY public."measurement_cycles" ADD CONSTRAINT "measurement_cycles_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."measurement_cycles" ADD CONSTRAINT "measurement_cycles_status_check" CHECK (status::text = ANY (ARRAY['IDLE'::character varying, 'FILLING'::character varying, 'STABILIZING'::character varying, 'MEASURING'::character varying, 'DRAINING'::character varying, 'COMPLETED'::character varying, 'ERROR'::character varying]::text[]));
ALTER TABLE ONLY public."notification_logs" ADD CONSTRAINT "notification_logs_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."ponds" ADD CONSTRAINT "ponds_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."relay_states" ADD CONSTRAINT "relay_states_current_state_check" CHECK (current_state::text = ANY (ARRAY['ON'::character varying, 'OFF'::character varying]::text[]));
ALTER TABLE ONLY public."relay_states" ADD CONSTRAINT "relay_states_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."relay_states" ADD CONSTRAINT "uknmhuw8e82uua4us2oklr7vkwb" UNIQUE (device_id, relay_no);
ALTER TABLE ONLY public."salinity_correction_cycles" ADD CONSTRAINT "salinity_correction_cycles_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."salinity_correction_cycles" ADD CONSTRAINT "salinity_correction_cycles_status_check" CHECK (status::text = ANY (ARRAY['SALINITY_HIGH_DETECTED'::character varying, 'DRAINING_SALTY_WATER'::character varying, 'ADDING_FRESH_WATER'::character varying, 'WAITING_MIXING'::character varying, 'RECHECKING'::character varying, 'COMPLETED'::character varying, 'NEED_MANUAL_CHECK'::character varying, 'ERROR'::character varying]::text[]));
ALTER TABLE ONLY public."sensor_calibrations" ADD CONSTRAINT "sensor_calibrations_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."sensor_readings" ADD CONSTRAINT "sensor_readings_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."sensor_readings" ADD CONSTRAINT "sensor_readings_status_check" CHECK (status::text = ANY (ARRAY['NORMAL'::character varying, 'WARNING'::character varying, 'DANGER'::character varying]::text[]));
ALTER TABLE ONLY public."threshold_configs" ADD CONSTRAINT "threshold_configs_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."threshold_configs" ADD CONSTRAINT "uk9tu27wlxqq21a5ksxw8dv9lro" UNIQUE (pond_id, parameter_name);
ALTER TABLE ONLY public."user_pond_access" ADD CONSTRAINT "ukp6v0khja3r24xaf1pb2c9l8ar" UNIQUE (user_id, pond_id);
ALTER TABLE ONLY public."user_pond_access" ADD CONSTRAINT "user_pond_access_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."users" ADD CONSTRAINT "uk6dotkott2kjsp8vw4d0m25fb7" UNIQUE (email);
ALTER TABLE ONLY public."users" ADD CONSTRAINT "ukr43af9ap4edm43mmtq01oddj6" UNIQUE (username);
ALTER TABLE ONLY public."users" ADD CONSTRAINT "users_approval_status_check" CHECK (approval_status::text = ANY (ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying]::text[]));
ALTER TABLE ONLY public."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public."users" ADD CONSTRAINT "users_role_check" CHECK (role::text = ANY (ARRAY['ADMIN'::character varying, 'USER'::character varying, 'TECHNICIAN'::character varying]::text[]));

ALTER TABLE ONLY public."auth_tokens" ADD CONSTRAINT "fkkhs4tpy3l5krnk87ykkmafeic" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY public."chat_messages" ADD CONSTRAINT "fk3cpkdtwdxndrjhrx3gt9q5ux9" FOREIGN KEY (session_id) REFERENCES chat_sessions(id);
ALTER TABLE ONLY public."chat_sessions" ADD CONSTRAINT "fk82ky97glaomlmhjqae1d0esmy" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY public."control_scenarios" ADD CONSTRAINT "fk5smi0knn3460atjwgpafrh9fl" FOREIGN KEY (pond_id) REFERENCES ponds(id);
ALTER TABLE ONLY public."device_provisioning" ADD CONSTRAINT "fk2mflls2t8jnopanbkhsta1wfe" FOREIGN KEY (claimed_by_user_id) REFERENCES users(id);
ALTER TABLE ONLY public."device_provisioning" ADD CONSTRAINT "fk907q6fpjk6n071bc4f60d0l2f" FOREIGN KEY (claimed_pond_id) REFERENCES ponds(id);
ALTER TABLE ONLY public."device_provisioning" ADD CONSTRAINT "fkkrc90s83qo01ibt1sgv0ou1vo" FOREIGN KEY (device_id) REFERENCES devices(id);
ALTER TABLE ONLY public."device_relays" ADD CONSTRAINT "fk9628qxopgl9xsnrfq743abjdj" FOREIGN KEY (device_id) REFERENCES devices(id);
ALTER TABLE ONLY public."device_sensors" ADD CONSTRAINT "fkpwwpo1oukdm1d5cue2eom4uv" FOREIGN KEY (device_id) REFERENCES devices(id);
ALTER TABLE ONLY public."devices" ADD CONSTRAINT "fkqs811syingmu8348gd2uapjsj" FOREIGN KEY (pond_id) REFERENCES ponds(id);
ALTER TABLE ONLY public."threshold_configs" ADD CONSTRAINT "fk964qqql4i3qjrkp1wqeg21jyv" FOREIGN KEY (pond_id) REFERENCES ponds(id);
ALTER TABLE ONLY public."user_pond_access" ADD CONSTRAINT "fk13ik5hyws3cu7wvet5g4t8818" FOREIGN KEY (pond_id) REFERENCES ponds(id);
ALTER TABLE ONLY public."user_pond_access" ADD CONSTRAINT "fkgv1wvxece81rxc1xdmarvkbec" FOREIGN KEY (user_id) REFERENCES users(id);

CREATE INDEX idx_device_commands_device_created ON public.device_commands USING btree (device_id, created_at);
CREATE INDEX idx_device_commands_device_status ON public.device_commands USING btree (device_id, status);
CREATE INDEX idx_device_commands_status_expires ON public.device_commands USING btree (status, expires_at);
CREATE INDEX idx_device_latest_states_updated_at ON public.device_latest_states USING btree (updated_at);
CREATE INDEX idx_notification_logs_device_time ON public.notification_logs USING btree (device_id, created_at);
CREATE INDEX idx_notification_logs_event_key_time ON public.notification_logs USING btree (event_key, created_at);
CREATE INDEX idx_notification_logs_status_time ON public.notification_logs USING btree (status, created_at);
CREATE INDEX idx_notification_logs_user_read_time ON public.notification_logs USING btree (recipient_user_id, read_flag, created_at);
CREATE INDEX idx_sensor_calibrations_created_at ON public.sensor_calibrations USING btree (created_at);
CREATE INDEX idx_sensor_calibrations_device_type ON public.sensor_calibrations USING btree (device_id, sensor_type, active);
CREATE INDEX idx_sensor_readings_device_time ON public.sensor_readings USING btree (device_id, created_at);
CREATE INDEX idx_sensor_readings_status_time ON public.sensor_readings USING btree (status, created_at);
